auth_enabled: false

server:
  http_listen_port: 3100
  http_tls_config:
    client_auth_type: NoClientCert  # Отключение требования клиентских сертификатов

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /loki/data  # Постоянная директория внутри контейнера

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb  # Используем boltdb для периода > 24h
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 168h  # Период 7 дней

storage_config:
  filesystem:
    directory: /loki/data/chunks  # Директория для чанков
  boltdb:
    directory: /loki/data/index  # Директория для индексов BoltDB

limits_config:
  allow_structured_metadata: false  # Отключение Structured Metadata
  retention_period: 720h  # 30 дней

compactor:
  working_directory: /loki/data/compactor  # Рабочая директория для компактора
  retention_enabled: true  # Включение retention
  delete_request_store: filesystem  # Указываем хранилище для запросов на удаление