services:
  db:
    restart: always
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data  # Используем volume для хранения данных
    ports:
      - "5432:5432"

  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    env_file:
      - ./auth/.env
    depends_on:
      - db
    ports:
      - "50055:50055"  # Это для локальной отладки, не обязательно

  dbservice:
    build:
      context: .
      dockerfile: ./dbservice/Dockerfile
    env_file:
      - ./dbservice/.env
    depends_on:
      - db
    ports:
      - "8081:8081"  # Это для локальной отладки, не обязательно


  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  db-data:  # Определяем volume db-data
