services:
  db:
    restart: always
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data  # Используем volume для хранения данных
    ports:
      - "5432:5432"

  auth:
    build:
      context: ./auth
    env_file:
      - ./auth/.env
    depends_on:
      - db
    ports:
      - "8081:8081"

  dbservice:
    build:
      context: ./dbservice
    env_file:
      - ./dbservice/.env
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db-data:  # Определяем volume db-data
