services:
  db:
    restart: always
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data  # Используем volume для хранения данных
    ports:
      - "5432:5432"

  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    env_file:
      - ./auth/.env
    depends_on:
      - db
    ports:
      - "50055:50055"

  admin_control:
    build:
      context: .
      dockerfile: ./admin_control/Dockerfile
    env_file:
      - ./admin_control/.env
    depends_on:
      - db
    ports:
      - "50070:50070"

  dbservice:
    build:
      context: .
      dockerfile: ./dbservice/Dockerfile
    env_file:
      - ./dbservice/.env
    depends_on:
      - db
    ports:
      - "8081:8081"  # Это для локальной отладки, не обязательно

  timer:
    build:
      context: .
      dockerfile: ./timer/Dockerfile
    env_file:
      - ./timer/.env
    depends_on:
      - db
    ports:
      - "50020:50020"  # Это для локальной отладки, не обязательно

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
  redis:
    build:
      context: . # Путь к директории с Dockerfile
      dockerfile: ./redis/Dockerfile # Указываем Dockerfile
    ports:
      - "50060:50060" # Пробрасываем порт для gRPC сервиса
      - "6379:6379"   # Пробрасываем порт для Redis (если требуется доступ извне)
    volumes:
      - redis_data:/data # Хранилище данных Redis

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: adminrmq
      RABBITMQ_DEFAULT_PASS: passconnectmq

  email-service:
      build:
        context: . # Путь к директории с Dockerfile
        dockerfile: ./email-service/Dockerfile # Указываем Dockerfile
      depends_on:
        - rabbitmq
      ports:
        - "50051:50051"

volumes:
  db-data:  # Определяем volume db-data
  redis_data:  # Объем данных для Redis
