// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: redis/proto/redis_service.proto

package redis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveRedisRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value      string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Expiration int64  `protobuf:"varint,3,opt,name=expiration,proto3" json:"expiration,omitempty"` // Время в секундах
}

func (x *SaveRedisRequest) Reset() {
	*x = SaveRedisRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_proto_redis_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveRedisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRedisRequest) ProtoMessage() {}

func (x *SaveRedisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_redis_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRedisRequest.ProtoReflect.Descriptor instead.
func (*SaveRedisRequest) Descriptor() ([]byte, []int) {
	return file_redis_proto_redis_service_proto_rawDescGZIP(), []int{0}
}

func (x *SaveRedisRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SaveRedisRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SaveRedisRequest) GetExpiration() int64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

type SaveRedisResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  uint32 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SaveRedisResponse) Reset() {
	*x = SaveRedisResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_proto_redis_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveRedisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRedisResponse) ProtoMessage() {}

func (x *SaveRedisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_redis_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRedisResponse.ProtoReflect.Descriptor instead.
func (*SaveRedisResponse) Descriptor() ([]byte, []int) {
	return file_redis_proto_redis_service_proto_rawDescGZIP(), []int{1}
}

func (x *SaveRedisResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SaveRedisResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRedisRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetRedisRequest) Reset() {
	*x = GetRedisRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_proto_redis_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRedisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedisRequest) ProtoMessage() {}

func (x *GetRedisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_redis_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedisRequest.ProtoReflect.Descriptor instead.
func (*GetRedisRequest) Descriptor() ([]byte, []int) {
	return file_redis_proto_redis_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetRedisRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetRedisResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  uint32 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetRedisResponse) Reset() {
	*x = GetRedisResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_proto_redis_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRedisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedisResponse) ProtoMessage() {}

func (x *GetRedisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_redis_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedisResponse.ProtoReflect.Descriptor instead.
func (*GetRedisResponse) Descriptor() ([]byte, []int) {
	return file_redis_proto_redis_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetRedisResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetRedisResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_redis_proto_redis_service_proto protoreflect.FileDescriptor

var file_redis_proto_redis_service_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x72, 0x65, 0x64, 0x69, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65,
	0x64, 0x69, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x22, 0x5a, 0x0a, 0x10,
	0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x64, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x45, 0x0a, 0x11, 0x53, 0x61, 0x76, 0x65,
	0x52, 0x65, 0x64, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x23, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x64, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0x44, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x64, 0x69, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x91, 0x01, 0x0a, 0x0c, 0x52,
	0x65, 0x64, 0x69, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x04, 0x53,
	0x61, 0x76, 0x65, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x2e,
	0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x64, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x2e, 0x53, 0x61, 0x76,
	0x65, 0x52, 0x65, 0x64, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e,
	0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x66, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x64, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x64, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x10,
	0x5a, 0x0e, 0x2e, 0x2f, 0x72, 0x65, 0x64, 0x69, 0x73, 0x2f, 0x3b, 0x72, 0x65, 0x64, 0x69, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_redis_proto_redis_service_proto_rawDescOnce sync.Once
	file_redis_proto_redis_service_proto_rawDescData = file_redis_proto_redis_service_proto_rawDesc
)

func file_redis_proto_redis_service_proto_rawDescGZIP() []byte {
	file_redis_proto_redis_service_proto_rawDescOnce.Do(func() {
		file_redis_proto_redis_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_redis_proto_redis_service_proto_rawDescData)
	})
	return file_redis_proto_redis_service_proto_rawDescData
}

var file_redis_proto_redis_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_redis_proto_redis_service_proto_goTypes = []any{
	(*SaveRedisRequest)(nil),  // 0: protobuff.SaveRedisRequest
	(*SaveRedisResponse)(nil), // 1: protobuff.SaveRedisResponse
	(*GetRedisRequest)(nil),   // 2: protobuff.GetRedisRequest
	(*GetRedisResponse)(nil),  // 3: protobuff.GetRedisResponse
}
var file_redis_proto_redis_service_proto_depIdxs = []int32{
	0, // 0: protobuff.RedisService.Save:input_type -> protobuff.SaveRedisRequest
	2, // 1: protobuff.RedisService.Get:input_type -> protobuff.GetRedisRequest
	1, // 2: protobuff.RedisService.Save:output_type -> protobuff.SaveRedisResponse
	3, // 3: protobuff.RedisService.Get:output_type -> protobuff.GetRedisResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_redis_proto_redis_service_proto_init() }
func file_redis_proto_redis_service_proto_init() {
	if File_redis_proto_redis_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_redis_proto_redis_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SaveRedisRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_proto_redis_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SaveRedisResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_proto_redis_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetRedisRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_proto_redis_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetRedisResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_redis_proto_redis_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_redis_proto_redis_service_proto_goTypes,
		DependencyIndexes: file_redis_proto_redis_service_proto_depIdxs,
		MessageInfos:      file_redis_proto_redis_service_proto_msgTypes,
	}.Build()
	File_redis_proto_redis_service_proto = out.File
	file_redis_proto_redis_service_proto_rawDesc = nil
	file_redis_proto_redis_service_proto_goTypes = nil
	file_redis_proto_redis_service_proto_depIdxs = nil
}
