CREATE TABLE IF NOT EXISTS users
(
    id   SERIAL PRIMARY KEY,
    roles VARCHAR(100) NOT NULL UNIQUE,
    company_id VARCHAR(100) NOT NULL UNIQUE,
    rightsId VARCHAR(100)  NOT NULL,
    authId VARCHAR(100)  NOT NULL UNIQUE
);
