// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: timer/proto/timer.proto

package timer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TimerService_StartTimer_FullMethodName      = "/protobuff.TimerService/StartTimer"
	TimerService_EndTimer_FullMethodName        = "/protobuff.TimerService/EndTimer"
	TimerService_GetWorkingTimer_FullMethodName = "/protobuff.TimerService/GetWorkingTimer"
	TimerService_ChangeTimer_FullMethodName     = "/protobuff.TimerService/ChangeTimer"
	TimerService_AddTimer_FullMethodName        = "/protobuff.TimerService/AddTimer"
)

// TimerServiceClient is the client API for TimerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TimerServiceClient interface {
	// Запускаем новый таймер
	StartTimer(ctx context.Context, in *StartEndTimerRequest, opts ...grpc.CallOption) (*StartEndTimerResponse, error)
	// Завершаем работу таймера
	EndTimer(ctx context.Context, in *StartEndTimerRequest, opts ...grpc.CallOption) (*StartEndTimerResponse, error)
	// Получаем активный таймер
	GetWorkingTimer(ctx context.Context, in *WorkingTimerRequest, opts ...grpc.CallOption) (*WorkingTimerResponse, error)
	// Изменяет таймер необходимым образом
	ChangeTimer(ctx context.Context, in *ChangeTimerRequest, opts ...grpc.CallOption) (*ChangeTimerResponse, error)
	// Добавляем необходимый таймер
	AddTimer(ctx context.Context, in *AddTimerRequest, opts ...grpc.CallOption) (*AddTimerResponse, error)
}

type timerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimerServiceClient(cc grpc.ClientConnInterface) TimerServiceClient {
	return &timerServiceClient{cc}
}

func (c *timerServiceClient) StartTimer(ctx context.Context, in *StartEndTimerRequest, opts ...grpc.CallOption) (*StartEndTimerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartEndTimerResponse)
	err := c.cc.Invoke(ctx, TimerService_StartTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timerServiceClient) EndTimer(ctx context.Context, in *StartEndTimerRequest, opts ...grpc.CallOption) (*StartEndTimerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartEndTimerResponse)
	err := c.cc.Invoke(ctx, TimerService_EndTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timerServiceClient) GetWorkingTimer(ctx context.Context, in *WorkingTimerRequest, opts ...grpc.CallOption) (*WorkingTimerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkingTimerResponse)
	err := c.cc.Invoke(ctx, TimerService_GetWorkingTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timerServiceClient) ChangeTimer(ctx context.Context, in *ChangeTimerRequest, opts ...grpc.CallOption) (*ChangeTimerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeTimerResponse)
	err := c.cc.Invoke(ctx, TimerService_ChangeTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timerServiceClient) AddTimer(ctx context.Context, in *AddTimerRequest, opts ...grpc.CallOption) (*AddTimerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTimerResponse)
	err := c.cc.Invoke(ctx, TimerService_AddTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimerServiceServer is the server API for TimerService service.
// All implementations must embed UnimplementedTimerServiceServer
// for forward compatibility.
type TimerServiceServer interface {
	// Запускаем новый таймер
	StartTimer(context.Context, *StartEndTimerRequest) (*StartEndTimerResponse, error)
	// Завершаем работу таймера
	EndTimer(context.Context, *StartEndTimerRequest) (*StartEndTimerResponse, error)
	// Получаем активный таймер
	GetWorkingTimer(context.Context, *WorkingTimerRequest) (*WorkingTimerResponse, error)
	// Изменяет таймер необходимым образом
	ChangeTimer(context.Context, *ChangeTimerRequest) (*ChangeTimerResponse, error)
	// Добавляем необходимый таймер
	AddTimer(context.Context, *AddTimerRequest) (*AddTimerResponse, error)
	mustEmbedUnimplementedTimerServiceServer()
}

// UnimplementedTimerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTimerServiceServer struct{}

func (UnimplementedTimerServiceServer) StartTimer(context.Context, *StartEndTimerRequest) (*StartEndTimerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTimer not implemented")
}
func (UnimplementedTimerServiceServer) EndTimer(context.Context, *StartEndTimerRequest) (*StartEndTimerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndTimer not implemented")
}
func (UnimplementedTimerServiceServer) GetWorkingTimer(context.Context, *WorkingTimerRequest) (*WorkingTimerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkingTimer not implemented")
}
func (UnimplementedTimerServiceServer) ChangeTimer(context.Context, *ChangeTimerRequest) (*ChangeTimerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeTimer not implemented")
}
func (UnimplementedTimerServiceServer) AddTimer(context.Context, *AddTimerRequest) (*AddTimerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTimer not implemented")
}
func (UnimplementedTimerServiceServer) mustEmbedUnimplementedTimerServiceServer() {}
func (UnimplementedTimerServiceServer) testEmbeddedByValue()                      {}

// UnsafeTimerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimerServiceServer will
// result in compilation errors.
type UnsafeTimerServiceServer interface {
	mustEmbedUnimplementedTimerServiceServer()
}

func RegisterTimerServiceServer(s grpc.ServiceRegistrar, srv TimerServiceServer) {
	// If the following call pancis, it indicates UnimplementedTimerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TimerService_ServiceDesc, srv)
}

func _TimerService_StartTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartEndTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimerServiceServer).StartTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimerService_StartTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimerServiceServer).StartTimer(ctx, req.(*StartEndTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimerService_EndTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartEndTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimerServiceServer).EndTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimerService_EndTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimerServiceServer).EndTimer(ctx, req.(*StartEndTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimerService_GetWorkingTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkingTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimerServiceServer).GetWorkingTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimerService_GetWorkingTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimerServiceServer).GetWorkingTimer(ctx, req.(*WorkingTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimerService_ChangeTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimerServiceServer).ChangeTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimerService_ChangeTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimerServiceServer).ChangeTimer(ctx, req.(*ChangeTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimerService_AddTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimerServiceServer).AddTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimerService_AddTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimerServiceServer).AddTimer(ctx, req.(*AddTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TimerService_ServiceDesc is the grpc.ServiceDesc for TimerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuff.TimerService",
	HandlerType: (*TimerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartTimer",
			Handler:    _TimerService_StartTimer_Handler,
		},
		{
			MethodName: "EndTimer",
			Handler:    _TimerService_EndTimer_Handler,
		},
		{
			MethodName: "GetWorkingTimer",
			Handler:    _TimerService_GetWorkingTimer_Handler,
		},
		{
			MethodName: "ChangeTimer",
			Handler:    _TimerService_ChangeTimer_Handler,
		},
		{
			MethodName: "AddTimer",
			Handler:    _TimerService_AddTimer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "timer/proto/timer.proto",
}
