# traefik/traefik_dynamic.yml
http:
  routers:
    auth:
      rule: "Host(`localhost`)"
      service: auth
      entryPoints:
        - web
    grpc-auth:
      rule: "Host(`localhost`)"
      service: auth
      entryPoints:
        - grpc

  services:
    auth:
      loadBalancer:
        servers:
          - url: "http://auth:50051" # Внутренний адрес auth сервиса
