// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: timer/proto/timer.proto

package timer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveTimerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DbName string `protobuf:"bytes,1,opt,name=dbName,proto3" json:"dbName,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *SaveTimerRequest) Reset() {
	*x = SaveTimerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timer_proto_timer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveTimerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTimerRequest) ProtoMessage() {}

func (x *SaveTimerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timer_proto_timer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTimerRequest.ProtoReflect.Descriptor instead.
func (*SaveTimerRequest) Descriptor() ([]byte, []int) {
	return file_timer_proto_timer_proto_rawDescGZIP(), []int{0}
}

func (x *SaveTimerRequest) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *SaveTimerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SaveTimerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status  uint32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SaveTimerResponse) Reset() {
	*x = SaveTimerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timer_proto_timer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveTimerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTimerResponse) ProtoMessage() {}

func (x *SaveTimerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timer_proto_timer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTimerResponse.ProtoReflect.Descriptor instead.
func (*SaveTimerResponse) Descriptor() ([]byte, []int) {
	return file_timer_proto_timer_proto_rawDescGZIP(), []int{1}
}

func (x *SaveTimerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SaveTimerResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetTimerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DbName string `protobuf:"bytes,1,opt,name=dbName,proto3" json:"dbName,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetTimerRequest) Reset() {
	*x = GetTimerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timer_proto_timer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTimerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimerRequest) ProtoMessage() {}

func (x *GetTimerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timer_proto_timer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimerRequest.ProtoReflect.Descriptor instead.
func (*GetTimerRequest) Descriptor() ([]byte, []int) {
	return file_timer_proto_timer_proto_rawDescGZIP(), []int{2}
}

func (x *GetTimerRequest) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *GetTimerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTimerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status  uint32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetTimerResponse) Reset() {
	*x = GetTimerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timer_proto_timer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTimerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimerResponse) ProtoMessage() {}

func (x *GetTimerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timer_proto_timer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimerResponse.ProtoReflect.Descriptor instead.
func (*GetTimerResponse) Descriptor() ([]byte, []int) {
	return file_timer_proto_timer_proto_rawDescGZIP(), []int{3}
}

func (x *GetTimerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTimerResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_timer_proto_timer_proto protoreflect.FileDescriptor

var file_timer_proto_timer_proto_rawDesc = []byte{
	0x0a, 0x17, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x66, 0x22, 0x42, 0x0a, 0x10, 0x53, 0x61, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x62, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x62, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x11, 0x53, 0x61, 0x76, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x41, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x64, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x44, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x9f, 0x01, 0x0a, 0x0c, 0x54, 0x69, 0x6d,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x09, 0x53, 0x61, 0x76,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x66, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x2e,
	0x53, 0x61, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x47, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x69, 0x6d, 0x65,
	0x72, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x72, 0x2f, 0x3b, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_timer_proto_timer_proto_rawDescOnce sync.Once
	file_timer_proto_timer_proto_rawDescData = file_timer_proto_timer_proto_rawDesc
)

func file_timer_proto_timer_proto_rawDescGZIP() []byte {
	file_timer_proto_timer_proto_rawDescOnce.Do(func() {
		file_timer_proto_timer_proto_rawDescData = protoimpl.X.CompressGZIP(file_timer_proto_timer_proto_rawDescData)
	})
	return file_timer_proto_timer_proto_rawDescData
}

var file_timer_proto_timer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_timer_proto_timer_proto_goTypes = []any{
	(*SaveTimerRequest)(nil),  // 0: protobuff.SaveTimerRequest
	(*SaveTimerResponse)(nil), // 1: protobuff.SaveTimerResponse
	(*GetTimerRequest)(nil),   // 2: protobuff.GetTimerRequest
	(*GetTimerResponse)(nil),  // 3: protobuff.GetTimerResponse
}
var file_timer_proto_timer_proto_depIdxs = []int32{
	0, // 0: protobuff.TimerService.SaveTimer:input_type -> protobuff.SaveTimerRequest
	2, // 1: protobuff.TimerService.GetOpenTimer:input_type -> protobuff.GetTimerRequest
	1, // 2: protobuff.TimerService.SaveTimer:output_type -> protobuff.SaveTimerResponse
	3, // 3: protobuff.TimerService.GetOpenTimer:output_type -> protobuff.GetTimerResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_timer_proto_timer_proto_init() }
func file_timer_proto_timer_proto_init() {
	if File_timer_proto_timer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_timer_proto_timer_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SaveTimerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timer_proto_timer_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SaveTimerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timer_proto_timer_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetTimerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timer_proto_timer_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetTimerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_timer_proto_timer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_timer_proto_timer_proto_goTypes,
		DependencyIndexes: file_timer_proto_timer_proto_depIdxs,
		MessageInfos:      file_timer_proto_timer_proto_msgTypes,
	}.Build()
	File_timer_proto_timer_proto = out.File
	file_timer_proto_timer_proto_rawDesc = nil
	file_timer_proto_timer_proto_goTypes = nil
	file_timer_proto_timer_proto_depIdxs = nil
}
